pipeline {
    agent any 
   
    
    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/Udeshiimasha/nodetest_jenkins'
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                bat 'docker build -t imashaudeshi/mynodeapp-cuban .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'test_dockerhub-password', variable: 'testdockerhub-password')]) {
    
               bat'docker login -u imashaudeshi -p ${testdockerhub-password}'
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push imashaudeshi/mynodeapp-cuban'
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
}
